name = "hex-bareiss-mathlib"
defaultTargets = ["HexBareissMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "365881fb205210e8d27c5eb011f7ddb3fe020373"

[[require]]
name = "HexDeterminantMathlib"
git = "https://github.com/leanprover/hex-determinant-mathlib.git"
rev = "50a067a2216e3fa17267b7a8444edb136b00e12d"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexBareissMathlib"
