name = "hex-bareiss-mathlib"
defaultTargets = ["HexBareissMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexDeterminantMathlib"
git = "https://github.com/leanprover/hex-determinant-mathlib.git"
rev = "e5d646df54cbe693a2c8deb094770dd977875a7b"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexBareissMathlib"
